theme: minima
markdown: kramdown
author: Domenico Cipriani
title: Music (and Sounds) with Pharo
description: "A guide to composing music and generating sounds in Pharo: blog and manuals for Coypu and Phausto"
paginate: 3 # This will show 3 posts per page
