remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
author: Domenico Cipriani
title: Music (and Sounds) with Pharo
description: "A guide to composing music and generating sounds in Pharo: blog and manuals for Coypu and Phausto"
